#!/usr/bin/env node

/**
 * Riffle Setup Script
 * Run: node scripts/setup.js
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

async function main() {
  console.log('\n🎣 Welcome to Riffle Setup!\n');
  console.log('This script will help you configure your environment.\n');
  console.log('You\'ll need:\n');
  console.log('  1. OpenAI API Key (for AI chatbot)');
  console.log('     Get one at: https://platform.openai.com/api-keys\n');
  console.log('  2. Stripe API Keys (for payments)');
  console.log('     Get them at: https://dashboard.stripe.com/test/apikeys\n');
  console.log('  3. OpenWeather API Key (optional, for weather)');
  console.log('     Get one at: https://openweathermap.org/api\n');

  const proceed = await question('Ready to continue? (y/n): ');
  if (proceed.toLowerCase() !== 'y') {
    console.log('\nRun this script again when you\'re ready!');
    rl.close();
    return;
  }

  console.log('\n--- API Keys ---\n');

  const openaiKey = await question('OpenAI API Key (sk-...): ');
  const stripeSecretKey = await question('Stripe Secret Key (sk_test_... or sk_live_...): ');
  const stripePriceId = await question('Stripe Price ID (price_...): ');
  const openweatherKey = await question('OpenWeather API Key (optional, press Enter to skip): ');

  // Generate a random JWT secret
  const jwtSecret = require('crypto').randomBytes(32).toString('hex');

  const envContent = `# Riffle Environment Variables
# Generated by setup script

# AI Chatbot
OPENAI_API_KEY=${openaiKey}

# Payments
STRIPE_SECRET_KEY=${stripeSecretKey}
STRIPE_PRICE_ID=${stripePriceId}
STRIPE_WEBHOOK_SECRET=

# Weather (optional)
OPENWEATHER_API_KEY=${openweatherKey}

# Security
JWT_SECRET=${jwtSecret}
`;

  const envPath = path.join(process.cwd(), '.env.local');
  fs.writeFileSync(envPath, envContent);

  console.log('\n✅ Environment file created: .env.local\n');

  // Create data directory
  const dataDir = path.join(process.cwd(), 'data');
  if (!fs.existsSync(dataDir)) {
    fs.mkdirSync(dataDir, { recursive: true });
    console.log('✅ Data directory created\n');
  }

  console.log('🎉 Setup complete!\n');
  console.log('Next steps:\n');
  console.log('  1. Run: npm install');
  console.log('  2. Run: npm run dev');
  console.log('  3. Open: http://localhost:3000\n');
  console.log('For Stripe webhooks in production:\n');
  console.log('  1. Go to Stripe Dashboard > Developers > Webhooks');
  console.log('  2. Add endpoint: https://your-domain.com/api/stripe/webhook');
  console.log('  3. Copy the webhook secret to .env.local\n');

  rl.close();
}

main().catch(console.error);
